[project]
name = "big-data-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lecamux-hux", email = "lecamux@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
big-data-framework = "big_data_framework:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
